### ISSUE TITLE
Problem with package.json "engines" value, when using yarn

### ISSUE THREAD

**Issue by esusekov** [misterfresh/react-easy-transition#15]
Hi,

I have a problem with installing this package using yarn instead of npm.
It says: 
```
error react-easy-transition@1.2.3: The engine "node" is incompatible with this module. Expected version "7.2.1".
error Found incompatible module
``` 

As I understood it's because of the value of `engines.node`, which in you case is strictly set to `7.2.1`. Could you change it to something like `4.x || 5.x || 6.x || 7.x` (it's example from react's package.json)?

Thanks!

**Comment by misterfresh** [comment]
will look into it thanks

**Comment by estaub** [comment]
I ran into this too.

**Comment by misterfresh** [comment]
It should be good now

**Comment by elstob** [comment]
Hi, this is an issue again now that 8.x is a thing.

**Comment by tlouth19** [comment]
Any update on this? Does not work with 8.x

**Comment by elstob** [comment]
@misterfresh - Created a PR that should resolve this. #22

**Comment by misterfresh** [comment]
Done

**Comment by matthew-b-payne** [comment]
Please publish a release that includes the change allowing for 10+
