### ISSUE TITLE
Latest react package warns about using prop types from the main package

### ISSUE THREAD

**Issue by notgiorgi** [misterfresh/react-easy-transition#20]
![image](https://user-images.githubusercontent.com/12987425/28515508-eec71c74-706e-11e7-8cac-dc0a101c7af2.png)

**Comment by misterfresh** [comment]
Thanks for the PR, will look into it

**Comment by hughbe** [comment]
Thanks for submitting a fix

**Comment by misterfresh** [comment]
Done
