### ISSUE TITLE
Problem with the package's dependencies

### ISSUE THREAD

**Issue by d-gubert** [misterfresh/react-easy-transition#6]
Hi,

I was having a problem with the package after cloning my project and running `npm install`.

When I ran my project, I was getting the following error on the console:

`Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's`render`method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

After some research and a `find . | grep react` inside my `node_modules` folder, I found out the package had another version of React inside its own `node_modules` folder and it was loading this different version of React on the client, thus leading to the error above.

Apparently, setting the dependency from `^0.14.0 || 15.0` to `^0.14.0 || ^15.0` solved the problem for me, but I think a more thorough checking of the compatibility with the latest version would be the proper solution.

**Comment by misterfresh** [comment]
Thanks for reporting, should be fixed now.
