### ISSUE TITLE
Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined

### ISSUE THREAD

**Issue by aikssen** [misterfresh/react-easy-transition#7]
I found this problem when I tried to use EasyTransition with a custom Loading component.
The component mount and unmount a children component depending of a flag.
When the component is unmount it fires this error:

```
Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined
```

**Comment by aikssen** [comment]
Here is the example:

```
import React, { Component } from 'react';
import { Panel } from 'react-bootstrap';
import EasyTransition from 'react-easy-transition';
import WLoading from '../widgets/WLoading';

export class WPanel extends Component {

    render() {
        const properties = {
            path: location.pathname,
            initialStyle: { opacity: 0 },
            transition: 'all 0.3s ease-in',
            finalStyle: { opacity: 1 }
        };

        const { children, loading, title } = this.props;

        return (
            <EasyTransition {...properties}>
                <Panel header={title} bsStyle="success">
                    {loading ? <WLoading /> : children}
                </Panel>
            </EasyTransition>
        );
    }
}

export default WPanel;
```

**Comment by misterfresh** [comment]
The value that controls the loading / unloading of the children should be the "path" prop. Your flag should be fed into the "path" prop of EasyTransition component.

**Comment by aikssen** [comment]
Actually my `loading` flag is a boolean that changes from `false` when the app is requesting data to the api, to `true` when the data is fetched correctly. 
The `path` property only accepts string values, but converting `loading` to a string makes that the animation/transition runs twice, when `loading` changes its value.

By setting the `path` prop with any string, this solves my problem, for now.

```
const properties = {
    path: 'foo',
    ...
};
```

**Comment by misterfresh** [comment]
thanks for providing a solution. not sure if a default value for path in the component could solve that for all users
